# Etapa 1: Build do React app
FROM node:20 as builder
WORKDIR /app

COPY . .
RUN npm install --legacy-peer-deps
RUN npm run build

# Etapa 2: Nginx para servir o app
FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
# Certifique-se de que o nginx.conf e env.sh estão no diretório raiz do frontend
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY env.sh /docker-entrypoint.d/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


