// src/database/migrations/20250123003-update-announcements-company-scope.ts
import { QueryInterface, DataTypes } from 'sequelize';

export default {
  up: async (queryInterface: QueryInterface) => {
    // Adicionar campo targetCompanyId para permitir informativos específicos por empresa
    await queryInterface.addColumn('Announcements', 'targetCompanyId', {
      type: DataTypes.INTEGER,
      allowNull: true,
      references: {
        model: 'Companies',
        key: 'id'
      },
      onUpdate: 'CASCADE',
      onDelete: 'SET NULL',
      comment: 'ID da empresa alvo. NULL = todas as empresas'
    });

    // Adicionar campo type para categorizar os informativos
    await queryInterface.addColumn('Announcements', 'type', {
      type: DataTypes.ENUM('general', 'birthday', 'system'),
      allowNull: false,
      defaultValue: 'general',
      comment: 'Tipo do informativo'
    });

    // Adicionar campo isAutoGenerated para identificar informativos automáticos
    await queryInterface.addColumn('Announcements', 'isAutoGenerated', {
      type: DataTypes.BOOLEAN,
      allowNull: false,
      defaultValue: false,
      comment: 'Informativo gerado automaticamente pelo sistema'
    });

    // Adicionar campo expiresAt para informativos temporários
    await queryInterface.addColumn('Announcements', 'expiresAt', {
      type: DataTypes.DATE,
      allowNull: true,
      comment: 'Data de expiração do informativo'
    });

    // Adicionar índices
    await queryInterface.addIndex('Announcements', ['targetCompanyId'], {
      name: 'idx_announcements_target_company_id'
    });

    await queryInterface.addIndex('Announcements', ['type'], {
      name: 'idx_announcements_type'
    });

    await queryInterface.addIndex('Announcements', ['isAutoGenerated'], {
      name: 'idx_announcements_auto_generated'
    });

    await queryInterface.addIndex('Announcements', ['expiresAt'], {
      name: 'idx_announcements_expires_at'
    });
  },

  down: async (queryInterface: QueryInterface) => {
    // Remover índices
    await queryInterface.removeIndex('Announcements', 'idx_announcements_target_company_id');
    await queryInterface.removeIndex('Announcements', 'idx_announcements_type');
    await queryInterface.removeIndex('Announcements', 'idx_announcements_auto_generated');
    await queryInterface.removeIndex('Announcements', 'idx_announcements_expires_at');

    // Remover colunas
    await queryInterface.removeColumn('Announcements', 'targetCompanyId');
    await queryInterface.removeColumn('Announcements', 'type');
    await queryInterface.removeColumn('Announcements', 'isAutoGenerated');
    await queryInterface.removeColumn('Announcements', 'expiresAt');
  }
};